[env:esp32-s3]
platform = espressif32@6.5.0
board = esp32-s3-n16r8-qspi
framework = arduino
board_build.arduino.memory_type = qio_qspi
upload_port = /dev/ttyACM0
upload_speed = 115200
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DFIRMWARE_VERSION=\"1.0.0\"
    -DLV_CONF_INCLUDE_SIMPLE
    -Isrc
lib_deps =
    lvgl/lvgl@^8.3.11
platform_packages =
    framework-arduinoespressif32@file:///home/bo/Downloads/esp32-2.0.14.zip
